language: node_js

node_js:
  - '0.8'
  - '0.10'

install:
  - sudo apt-get install cmake
  - npm install -g npm
  - npm install

script:
  - npm run pretest
  - npm run test-verbose

notifications:
  email:
    on_success: change
    on_failure: always
