language: node_js

node_js:
  - "0.6"
  - "0.8"
  - "0.9"
  - "0.10"
  - "0.11"

install:
  - sudo apt-get install cmake

script:
  - npm install .
  - cmake .
  - ctest -VV --output-on-failure .

notifications:
  email:
    on_success: change
    on_failure: always
